# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteEngine', '0003_auto_20160621_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='supervisor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siteEngine.UserProfile'),
        ),
    ]
