# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 07:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteEngine', '0004_auto_20160621_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleAdmin',
            fields=[
                ('role_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='siteEngine.Role')),
            ],
            bases=('siteEngine.role',),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_auth',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
