# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteEngine', '0006_auto_20160624_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
